import type { Metadata } from 'next';
import { Inter, Antonio } from 'next/font/google';
import './globals.css';

const antonio = Antonio({
	variable: '--font-antonio',
	weight: 'variable',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${antonio.variable}`}> {children}</body>
		</html>
	);
}
